# Generated by Django 5.2.1 on 2025-05-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='fuente',
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
