# Generated by Django 5.2.2 on 2025-06-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medioamigo',
            name='medio',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
