# Generated by Django 5.2.1 on 2025-05-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatorio', '0003_suscriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='autor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
