# Generated by Django 5.2.2 on 2025-06-10 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observatorio', '0004_informe_adjustments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='palabra_clave',
        ),
    ]
