# Generated by Django 5.2.1 on 2025-05-30 00:00
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observatorio', '0005_informe_indexes'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='informes_pdf/'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                (
                    'informe',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comentarios',
                        to='observatorio.informe',
                    ),
                ),
                (
                    'usuario',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
                ),
            ],
            options={'ordering': ['-fecha']},
        ),
        migrations.CreateModel(
            name='MedioAmigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enlace', models.URLField()),
                ('resumen', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['titulo'],
                'verbose_name': 'medio amigo',
                'verbose_name_plural': 'medios amigos',
            },
        ),
    ]
