# Generated by Django 5.2.1 on 2025-06-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observatorio', '0006_auto_add_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='informe',
            options={'ordering': ['-fecha']},
        ),
    ]
