# Generated by Django 5.2.2 on 2025-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatorio', '0007_alter_categoria_options_alter_informe_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='documento',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
